use_default_settings: true

server:
  secret_key: "boomerang-searxng-secret"
  limiter: false

search:
  safe_search: 0
  default_lang: "fr"

outgoing:
  request_timeout: 10.0

engines:
  - name: google
    engine: google
    language: fr
    categories: general
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    language: fr
    categories: general
    disabled: false

formats:
  - html
  - json
