cookie:
  expiry_days: 30
  key: boomerang_auth_cookie_key
  name: boomerang_auth

credentials:
  usernames:
    admin:
      email: admin@boomerang.local
      name: Administrateur
      password: "$2b$12$FVAlkrlCietJwqdMyazgS.psZoYg7UrcGslVK0rPZ.C7urraIi//q"  # admin123
    architecte:
      email: archi@boomerang.local
      name: Architecte
      password: "$2b$12$iXqDgjckeXDkjRIBvJZiQ.3Vcb5S.yx/ecok8uBhE/lS7sytWUjO2"  # archi2026
